language: R
cache: packages
sudo: false
warnings_are_errors: false

r_packages:
  - covr
  - drat

r_github_packages:
  - OHDSI/DatabaseConnector

before_install:
  - Rscript -e 'update.packages(ask = FALSE)'
  - export LD_LIBRARY_PATH=$JAVA_HOME:$LD_LIBRARY_PATH

script: 
  - |
    R CMD build .
    travis_wait 30 R CMD check Achilles*tar.gz

notifications:
  recipients:
    - cknoll1@its.jnj.com
    - schuemie@ohdsi.org
  email:
    on_success: change
    on_failure: change

after_success:
  - travis_wait 30 Rscript -e 'library(covr);codecov()'
  # Rebuild docker container
  - curl --data "build=true" -X POST https://registry.hub.docker.com/u/ohdsi/broadsea-methodslibrary/trigger/f0b51cec-4027-4781-9383-4b38b42dd4f5/
  # Rebuild drat repo
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh

after_failure:
- find *Rcheck -name '*.fail' -print -exec cat '{}' \;

env:
  global:
    secure: a1Rdhif0jhUZRpNqLzIYbEBCM/+VbbTJhT3/vfxZKy+PiLVQixi/ARqvA581p/JRfsA3d9koWynxy6+karOKw94b27+Uaos8ds85noObq3enND+d/FNVqDA9mn9l0tDFioeKR7T2SQlyWF1LIWtKzj9L21/EjNSy8mi0btiiJaU=
