#!/usr/bin/Rscript

# Load Achilles and httr.
library(Achilles)
library(httr)

# Get passed environment variables.
env_var_names <- list("ACHILLES_SITE", "ACHILLES_DB_URI",
                      "ACHILLES_CDM_SCHEMA", "ACHILLES_RES_SCHEMA",
                      "ACHILLES_OUTPUT_BASE", "ACHILLES_CDM_VERSION")
env_vars <- Sys.getenv(env_var_names, unset=NA)

# Replace unset environement variables with defaults.
default_vars <- list("DefaultSite", "postgresql://localhost/postgres",
                     "public", "public", "./output", "5")
env_vars[is.na(env_vars)] <- default_vars[is.na(env_vars)]

# Create name to tag results and output path from ACHILLES_SITE and timestamp
current_datetime <- strftime(Sys.time(), format="%Y-%m-%dT%H:%M:%S")
src_name <- paste(env_vars$ACHILLES_SITE, current_datetime, sep=" ")
output_path <- paste(env_vars$ACHILLES_OUTPUT_BASE, env_vars$ACHILLES_SITE,
                     current_datetime, sep="/")
dir.create(output_path, showWarnings=FALSE, recursive=TRUE, mode="0755")

# Parse DB URI into pieces.
db_conf <- parse_url(env_vars$ACHILLES_DB_URI)

# Some connection packages need the database on the server argument.
server <- paste(db_conf$hostname, db_conf$path, sep="/")

# Create connection details using DatabaseConnector utility.
connectionDetails <- createConnectionDetails(
    dbms=db_conf$scheme, user=db_conf$username, password=db_conf$password,
    server=server, schema=db_conf$path, port=db_conf$port
)

# Run Achilles report and generate data in the results schema.
achillesResults <- achilles(
    connectionDetails, cdmDatabaseSchema=env_vars$ACHILLES_CDM_SCHEMA,
    resultsDatabaseSchema=env_vars$ACHILLES_RES_SCHEMA, sourceName=src_name,
    cdmVersion=env_vars$ACHILLES_CDM_VERSION
)

# Export Achilles results to output path in JSON format.
exportToJson(
    connectionDetails, cdmDatabaseSchema=env_vars$ACHILLES_CDM_SCHEMA,
    resultsDatabaseSchema=env_vars$ACHILLES_RES_SCHEMA, outputPath=output_path,
    cdmVersion=env_vars$ACHILLES_CDM_VERSION
)
