# @file Achilles
#
# Copyright 2014 Observational Health Data Sciences and Informatics
#
# This file is part of Achilles
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# @author Observational Health Data Sciences and Informatics
# @author Martijn Schuemie
# @author Patrick Ryan

#' Get all analysis details
#' 
#' @details 
#' Get a list of all analyses with their analysis IDs and strata.
#' 
#' @return 
#' A data.frame with the analysis details.
#' 
#' @export
getAnalysisDetails <- function() {
  pathToCsv <- system.file("csv", "analysisDetails.csv", package = "Achilles")
  analysisDetails <- utils::read.csv(pathToCsv)
  return(analysisDetails)
}

#' The main Achilles analysis
#'
#' @description
#' \code{achilles} creates descriptive statistics summary for an entire OMOP CDM instance.
#'
#' @details
#' \code{achilles} creates descriptive statistics summary for an entire OMOP CDM instance.
#' 
#' @param connectionDetails  An R object of type ConnectionDetail (details for the function that contains server info, database type, optionally username/password, port)
#' @param cdmDatabaseSchema    	string name of database schema that contains OMOP CDM. On SQL Server, this should specifiy both the database and the schema, so for example 'cdm_instance.dbo'.
#' @param oracleTempSchema    For Oracle only: the name of the database schema where you want all temporary tables to be managed. Requires create/insert permissions to this database. 
#' @param resultsDatabaseSchema		string name of database schema that we can write results to. Default is cdmDatabaseSchema. On SQL Server, this should specifiy both the database and the schema, so for example 'results.dbo'.
#' @param sourceName		string name of the database, as recorded in results
#' @param analysisIds		(optional) a vector containing the set of Achilles analysisIds for which results will be generated.
#' If not specified, all analyses will be executed. Use \code{\link{getAnalysisDetails}} to get a list of all Achilles analyses and their Ids.
#' @param createTable     If true, new results tables will be created in the results schema. If not, the tables are assumed to already exists, and analysis results will be added
#' @param smallcellcount     To avoid patient identifiability, cells with small counts (<= smallcellcount) are deleted.
#' @param cdmVersion     Define the OMOP CDM version used:  currently support "4" and "5".  Default = "4"
#' @param runHeel     Boolean to determine if Achilles Heel data quality reporting will be produced based on the summary statistics.  Default = TRUE
#' @param validateSchema     Boolean to determine if CDM Schema Validation should be run. This could be very slow.  Default = FALSE
#' @param vocabDatabaseSchema		string name of database schema that contains OMOP Vocabulary. Default is cdmDatabaseSchema. On SQL Server, this should specifiy both the database and the schema, so for example 'results.dbo'.
#' @param sqlOnly Boolean to determine if the SQL generated by this function call should be executed or simply returned as a string. DEFAULT = FALSE indicating that the SQL code should be executed.
#' @param runCostAnalysis Boolean to determine if cost analysis should be run. Note: only works on CDM v5.0 style cost tables.
#' @param conceptHierarchy Boolean to determine if the concept_hierarchy result table should be created, for use by Atlas treemaps. Note: only works on CDM v5.0 tables.
#' @param createIndices Boolean to determine if indices should be created on the resulting Achilles and concept_hierarchy table. Default= TRUE
#' 
#' @return An object of type \code{achillesResults} containing details for connecting to the database containing the results 
#' @examples \dontrun{
#'   connectionDetails <- DatabaseConnector::createConnectionDetails(dbms="sql server", server="myserver")
#'   achillesResults <- achilles(connectionDetails, cdmDatabaseSchema="cdm4_sim", resultsDatabaseSchema="scratch", sourceName="TestDB", validateSchema="TRUE", vocabDatabaseSchema="vocabulary")
#'   fetchAchillesAnalysisResults(connectionDetails, "scratch", 106)
#' }
#' @export
achilles <- function (connectionDetails, 
                      cdmDatabaseSchema, 
                      oracleTempSchema = cdmDatabaseSchema,
                      resultsDatabaseSchema = cdmDatabaseSchema, 
                      sourceName = "", 
                      analysisIds, 
                      createTable = TRUE, 
                      smallcellcount = 5, 
                      cdmVersion = "4", 
                      runHeel = TRUE,
                      validateSchema = FALSE,
                      vocabDatabaseSchema = cdmDatabaseSchema,
                      runCostAnalysis = FALSE,
                      sqlOnly = FALSE,
                      conceptHierarchy = TRUE,
                      createIndices = TRUE){
  
  if (cdmVersion == "4")  {
    achillesFile <- "Achilles_v4.sql"
    heelFile <- "AchillesHeel_v4.sql"
    hierarchyFile = ""
    conceptHierarchy = FALSE
  } else if (cdmVersion == "5") {
    achillesFile <- "Achilles_v5.sql"
    heelFile <- "AchillesHeel_v5.sql"
    hierarchyFile = "ConceptHierarchy_v5.sql"
  } else  {
    stop("Error: Invalid CDM Version number, use 4 or 5")
  }
  
  if (missing(analysisIds))
    analysisIds = getAnalysisDetails()$ANALYSIS_ID
  
#   cdmDatabase <- strsplit(cdmDatabaseSchema ,"\\.")[[1]][1]
#   resultsDatabase <- strsplit(resultsDatabaseSchema ,"\\.")[[1]][1]
#   vocabDatabase <- strsplit(vocabDatabaseSchema ,"\\.")[[1]][1]
  
  achillesSql <- SqlRender::loadRenderTranslateSql(sqlFilename = achillesFile,
                                        packageName = "Achilles",
                                        dbms = connectionDetails$dbms,
                                        oracleTempSchema = oracleTempSchema,
                                        # cdm_database = cdmDatabase,
                                        cdm_database_schema = cdmDatabaseSchema,
                                        # results_database = resultsDatabase, 
                                        results_database_schema = resultsDatabaseSchema,
                                        source_name = sourceName, 
                                        list_of_analysis_ids = analysisIds,
                                        createTable = createTable,
                                        smallcellcount = smallcellcount,
                                        validateSchema = validateSchema,
                                        # vocab_database = vocabDatabase,
                                        # vocab_database_schema = vocabDatabaseSchema,
                                        runCostAnalysis = runCostAnalysis
  )
  
  if (sqlOnly) {
    outputFolder <- "output";
  
    if (!file.exists(outputFolder))
      dir.create(outputFolder);
    SqlRender::writeSql(achillesSql,paste(outputFolder, achillesFile, sep="/"));
    
    writeLines(paste("Achilles sql generated in: ", paste(outputFolder, achillesFile, sep="/")));
    
    return();
  } else {
    conn <- DatabaseConnector::connect(connectionDetails)
    writeLines("Executing multiple queries. This could take a while")
    #SqlRender::writeSql(achillesSql, 'achillesDebug.sql');
    DatabaseConnector::executeSql(conn,achillesSql)
    writeLines(paste("Done. Achilles results can now be found in",resultsDatabaseSchema))
  }
  
  if (runHeel) {
    heelSql <- SqlRender::loadRenderTranslateSql(sqlFilename = heelFile,
                                      packageName = "Achilles",
                                      dbms = connectionDetails$dbms,
                                      oracleTempSchema = oracleTempSchema,
                                      cdm_database_schema = cdmDatabaseSchema,
                                      # results_database = resultsDatabase,
                                      results_database_schema = resultsDatabaseSchema,
                                      source_name = sourceName, 
                                      #list_of_analysis_ids = analysisIds,
                                      createTable = createTable,
                                      smallcellcount = smallcellcount,
                                      # vocab_database = vocabDatabase,
                                      vocab_database_schema = vocabDatabaseSchema
    )
    
    writeLines("Executing Achilles Heel. This could take a while")
    DatabaseConnector::executeSql(conn,heelSql)
    writeLines(paste("Done. Achilles Heel results can now be found in",resultsDatabaseSchema))    
    
  } else heelSql='HEEL EXECUTION SKIPPED PER USER REQUEST'
  
  if (conceptHierarchy) {
    hierarchySql <- SqlRender::loadRenderTranslateSql(sqlFilename = hierarchyFile,
                                      packageName = "Achilles",
                                      dbms = connectionDetails$dbms,
                                      oracleTempSchema = oracleTempSchema,
                                      results_database_schema = resultsDatabaseSchema,
                                      vocab_database_schema = vocabDatabaseSchema
    )
    
    writeLines("Executing Concept Hierarchy creation. This could take a while")
    DatabaseConnector::executeSql(conn,hierarchySql)
    writeLines(paste("Done. Concept Hierarchy table can now be found in",resultsDatabaseSchema))    
    
  } else heelSql='CONCEPT HIERARCHY EXECUTION SKIPPED PER USER REQUEST'
  
  if (createIndices) {
    indicesSql <- createIndices(connectionDetails = connectionDetails,
                  resultsDatabaseSchema = resultsDatabaseSchema,
                  cdmVersion = cdmVersion)
  } else {
    indicesSql = "INDEX CREATION SKIPPED PER USER REQUEST"
  }
  
  DatabaseConnector::disconnect(conn)
  
  resultsConnectionDetails <- connectionDetails
  resultsConnectionDetails$schema = resultsDatabaseSchema
  result <- list(resultsConnectionDetails = resultsConnectionDetails, 
                 resultsTable = "ACHILLES_results",
                 resultsDistributionTable ="ACHILLES_results_dist",
                 analysis_table = "ACHILLES_analysis",
                 sourceName = sourceName,
                 analysisIds = analysisIds,
                 AchillesSql = achillesSql,
                 HeelSql = heelSql, #if runHeel is false -  this assignment fails - causes error of the  whole function  (adding else)
                 call = match.call())
  class(result) <- "achillesResults"
  result
}

#' execution of data quality rules 
#'
#' @description
#' \code{achillesHeel} executes data quality rules (or checks) on pre-computed analyses (or measures).
#'
#' @details
#' \code{achillesHeel} contains number of rules (authored in SQL) that are executed againts achilles results tables.
#' 
#' @param connectionDetails  An R object of type ConnectionDetail (details for the function that contains server info, database type, optionally username/password, port)
#' @param cdmDatabaseSchema    	string name of database schema that contains OMOP CDM. On SQL Server, this should specifiy both the database and the schema, so for example 'cdm_instance.dbo'.
#' @param oracleTempSchema    For Oracle only: the name of the database schema where you want all temporary tables to be managed. Requires create/insert permissions to this database. 
#' @param resultsDatabaseSchema		string name of database schema that we can write results to. Default is cdmDatabaseSchema. On SQL Server, this should specifiy both the database and the schema, so for example 'results.dbo'.
#' @param cdmVersion     Define the OMOP CDM version used:  currently support "4" and "5".  Default = "4"
#' @param vocabDatabaseSchema		string name of database schema that contains OMOP Vocabulary. Default is cdmDatabaseSchema. On SQL Server, this should specifiy both the database and the schema, so for example 'results.dbo'.
#' 
#' @return nothing is returned
#' @examples \dontrun{
#'   connectionDetails <- DatabaseConnector::createConnectionDetails(dbms="sql server", server="myserver")
#'   achillesHeel <- achilles(connectionDetails, cdmDatabaseSchema="mycdm", resultsDatabaseSchema="scratch", vocabDatabaseSchema="vocabulary")
#' }
#' @export
achillesHeel <- function (connectionDetails, 
                          cdmDatabaseSchema, 
                          oracleTempSchema = cdmDatabaseSchema,
                          resultsDatabaseSchema = cdmDatabaseSchema,
                          cdmVersion = "5",
                          vocabDatabaseSchema = cdmDatabaseSchema){
  
#   resultsDatabase <- strsplit(resultsDatabaseSchema ,"\\.")[[1]][1]
#   vocabDatabase <- strsplit(vocabDatabaseSchema ,"\\.")[[1]][1]
  
  if (cdmVersion == "4")  {
    heelFile <- "AchillesHeel_v4.sql"
  } else if (cdmVersion == "5") {
    heelFile <- "AchillesHeel_v5.sql"
  } else  {
    stop("Error: Invalid CDM Version number, use 4 or 5")
  }
  
  heelSql <- SqlRender::loadRenderTranslateSql(sqlFilename = heelFile,
                                    packageName = "Achilles",
                                    dbms = connectionDetails$dbms,
                                    oracleTempSchema = oracleTempSchema,
                                    cdm_database_schema = cdmDatabaseSchema,
                                    # results_database = resultsDatabase,
                                    results_database_schema = resultsDatabaseSchema,
                                    # vocab_database = vocabDatabase,
                                    vocab_database_schema = vocabDatabaseSchema
  );
  
  conn <- DatabaseConnector::connect(connectionDetails);
  writeLines("Executing Achilles Heel. This could take a while");
  DatabaseConnector::executeSql(conn,heelSql);
  DatabaseConnector::disconnect(conn);
  writeLines(paste("Done. Achilles Heel results can now be found in",resultsDatabaseSchema))
}

#new function to extract Heel resutls now when there are extra columns from inside R
#' @export
fetchAchillesHeelResults <- function (connectionDetails, resultsDatabaseSchema){
  connectionDetails$schema = resultsDatabaseSchema
  conn <- DatabaseConnector::connect(connectionDetails)
  
  
  sql <- "SELECT * FROM ACHILLES_heel_results"
  sql <- SqlRender::renderSql(sql)$sql
  res <- DatabaseConnector::querySql(conn,sql)
  DatabaseConnector::disconnect(conn)
  res
}

#' execution of concept hierarchy creation 
#'
#' @description
#' \code{conceptHierarchy} executes script to create the concept_hierarchy table.
#'
#' @details
#' \code{conceptHierarchy} executes script to create the concept_hierarchy table in the results schema, to be used by Atlas for treemap displays.
#' 
#' @param connectionDetails  An R object of type ConnectionDetail (details for the function that contains server info, database type, optionally username/password, port)
#' @param vocabDatabaseSchema		string name of database schema that contains OMOP Vocabulary. Default is vocabDatabaseSchema. On SQL Server, this should specifiy both the database and the schema, so for example 'results.dbo'.
#' @param oracleTempSchema    For Oracle only: the name of the database schema where you want all temporary tables to be managed. Requires create/insert permissions to this database. 
#' @param resultsDatabaseSchema		string name of database schema that we can write results to. Default is vocabDatabaseSchema. On SQL Server, this should specifiy both the database and the schema, so for example 'results.dbo'.
#' @param cdmVersion     Define the OMOP CDM version used:  currently support only "5".  Default = "5"
#' 
#' @return nothing is returned
#' @examples \dontrun{
#'   connectionDetails <- DatabaseConnector::createConnectionDetails(dbms="sql server", server="myserver")
#'   conceptHierarchy <- conceptHierarchy(connectionDetails, resultsDatabaseSchema="scratch", vocabDatabaseSchema="vocabulary")
#' }
#' @export
conceptHierarchy <- function (connectionDetails, 
                              vocabDatabaseSchema, 
                              oracleTempSchema = vocabDatabaseSchema,
                              resultsDatabaseSchema = vocabDatabaseSchema,
                              cdmVersion = "5"){
  
  #   resultsDatabase <- strsplit(resultsDatabaseSchema ,"\\.")[[1]][1]
  #   vocabDatabase <- strsplit(vocabDatabaseSchema ,"\\.")[[1]][1]
  
  if (cdmVersion == "5") {
    hierarchyFile = "ConceptHierarchy_v5.sql"
  } else  {
    stop("Error: Invalid CDM Version number, only version 5 supported")
  }
  
  hierarchySql <- SqlRender::loadRenderTranslateSql(sqlFilename = hierarchyFile,
                                         packageName = "Achilles",
                                         dbms = connectionDetails$dbms,
                                         oracleTempSchema = oracleTempSchema,
                                         #cdm_database_schema = cdmDatabaseSchema,
                                         results_database_schema = resultsDatabaseSchema,
                                         vocab_database_schema = vocabDatabaseSchema
  );
  
  conn <- DatabaseConnector::connect(connectionDetails);
  writeLines("Executing Concept Hierarchy creation. This could take a while")
  DatabaseConnector::executeSql(conn,hierarchySql)
  writeLines(paste("Done. Concept Hierarchy table can now be found in",resultsDatabaseSchema))    
}


#' Create indices on Achilles results tables and concept hierarchy
#'
#' @description
#' \code{createIndices} executes script to create indicies on the Achilles tables.
#'
#' @details
#' \code{createIndices} executes script to create indicies on the Achilles tables.
#' 
#' @param connectionDetails  An R object of type ConnectionDetail (details for the function that contains server info, database type, optionally username/password, port)
#' @param resultsDatabaseSchema		string name of database schema that holds the results tables for indexing. On SQL Server, this should specifiy both the database and the schema, so for example 'results.dbo'.
#' @param oracleTempSchema    For Oracle only: the name of the database schema where you want all temporary tables to be managed. Requires create/insert permissions to this database. 
#' @param cdmVersion     Define the OMOP CDM version used:  currently support only "5".  Default = "5"
#' 
#' @return nothing is returned
#' @examples \dontrun{
#'   connectionDetails <- DatabaseConnector::createConnectionDetails(dbms="sql server", server="myserver")
#'   createIndices <- createIndices(connectionDetails, resultsDatabaseSchema="scratch")
#' }
#' @export
createIndices <- function (connectionDetails, 
                           resultsDatabaseSchema,
                           oracleTempSchema = resultsDatabaseSchema,
                           sqlOnly = FALSE,
                           cdmVersion = "5"){
  
  if (cdmVersion == "5") {
    sqlFile = "Achilles_indices_v5.sql"
  } else  {
    stop("Error: Invalid CDM Version number, only version 5 supported")
  }
  
  if (connectionDetails$dbms=='redshift') {
    stop("Error: RedShift does not support creating indices")
  }
  
  is_pdw <- (connectionDetails$dbms == "pdw")
  
  indicesSql <- SqlRender::loadRenderTranslateSql(sqlFilename = sqlFile,
                                         packageName = "Achilles",
                                         dbms = connectionDetails$dbms,
                                         oracleTempSchema = oracleTempSchema,
                                         is_pdw = is_pdw,
                                         results_database_schema = resultsDatabaseSchema);
  
  if (!sqlOnly) {
    conn <- DatabaseConnector::connect(connectionDetails);
    writeLines("Executing indices creation. This could take a while")
    DatabaseConnector::executeSql(conn,indicesSql)
    writeLines(paste("Done. Indices created in",resultsDatabaseSchema))  
  }
  return(indicesSql)
}

