# @file exportToJson
#
# Copyright 2014 Observational Health Data Sciences and Informatics
#
# This file is part of Achilles
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


#' @title addDatasource
#'
#' @description
#' \code{addDatasource} adds a data source to the datasource.json file.
#'
#' @details
#' Used to update the datasources file with the reference to a specified datasource.
#' This makes the new datasource findable for OHDSI tools.
#' If the datasources file exists, the data source will be added to the file.
#' If the datasources file does not exist, a new file wil be initialized with the specified data source.
#' 
#' @param jsonFolderPath      Path of the Json files generated by \code{exportToJson}.
#' @param dataName  		Name of Achilles report. Default is the base folder of \code{jsonFolderPath}.
#' @param datasourcePath  Path where datasource file will be saved. Default is one folder above the \code{jsonFolderPath}
#' @param datasourcesFilename		Name of the file where the datasource is located or stored. Default is "datasources.json".
#' @param additionalParam  A R list specifying which additinal parameters to write to the datasource object. Default is \code{list(cdmVersion=5)}. 
#' 
#' @return none 
#' 
#' @examples \dontrun{
#' jsonFolderPath <- "your/output/path"
#' connectionDetails <- DatabaseConnector::createConnectionDetails(dbms="sql server", server="yourserver")
#' exportToJson(connectionDetails, cdmDatabaseSchema="cdm5", outputPath=jsonFolderPath)
#' addDatasource(jsonFolderPath, "your_data_name")
#' }
#' @export
addDatasource <- function(jsonFolderPath, dataName = NULL, datasourcePath = NULL, datasourcesFilename = "datasources.json", additionalParam = list(cdmVersion = 5) )
{
  # Parse the folder path.
  folderName <- basename(jsonFolderPath)
  if( is.null(dataName) ){
    dataName <- folderName
  }
  
  # Path to data source file
  if( is.null(datasourcePath) ){
    datasourcePath <- file.path( dirname(jsonFolderPath), datasourcesFilename )  
  }
  
  # Read the json file or create new if not exists
  if( file.exists(datasourcePath) ){
    print(paste("Writing to existing datasources file: ", datasourcePath))
    j <- rjson::fromJSON( file = datasourcePath )
  } else {
    print(paste("Creating a new datasources file: ", datasourcePath))
    j <- rjson::fromJSON('{"datasources":[]}')
  }
  
  # Append new datasource object to existing datasources
  n_elements <- length(j$datasources)
  new_datasource <- c(name=dataName, folder=folderName, additionalParam)
  j$datasources[[n_elements+1]] <- new_datasource
  
  # Overwrite existing json file
  write(rjson::toJSON(j), datasourcePath)
}

